name: CI build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build artifacts
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]')"
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build webUI
        run: |
          yarn build
          yarn build-zip
          yarn build-md5

          ls -lah buildZip

      - name: Generate Tag Name
        id: GenTagName
        run: |
          genTag="r$(git rev-list HEAD --count)"
          echo "$genTag"
          echo "::set-output name=value::$genTag"

      - name: Create Git Tag
        run: |
          TAG="${{ steps.GenTagName.outputs.value }}"

          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git tag "$TAG"
          git push origin "$TAG"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ github.token }}
          artifacts: "buildZip/*"
          tag: ${{ steps.GenTagName.outputs.value }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ github.token }}
          publish_dir: ./build
